// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameBanner = "banners"

// Banner 轮播图表
type Banner struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                                                       // 主键ID
	StationID int64          `gorm:"column:station_id;type:bigint;not null;index:idx_banners_station_status,priority:1;comment:ç«™ç‚¹ID(0=å¹³å°çº§/å…¨å±€)" json:"station_id"`        // ç«™ç‚¹ID(0=å¹³å°çº§/å…¨å±€)
	Title     string         `gorm:"column:title;type:varchar(100);comment:æ ‡é¢˜" json:"title"`                                                                                       // æ ‡é¢˜
	ImageURL  string         `gorm:"column:image_url;type:varchar(255);not null;comment:å›¾ç‰‡URL" json:"image_url"`                                                                   // å›¾ç‰‡URL
	LinkType  string         `gorm:"column:link_type;type:varchar(20);not null;default:none;comment:è·³è½¬ç±»åž‹(none/news/url)" json:"link_type"`                                     // è·³è½¬ç±»åž‹(none/news/url)
	LinkValue string         `gorm:"column:link_value;type:varchar(255);comment:è·³è½¬å€¼(æ–°é—»IDæˆ–URL)" json:"link_value"`                                                          // è·³è½¬å€¼(æ–°é—»IDæˆ–URL)
	Sort      int32          `gorm:"column:sort;type:int;not null;comment:æŽ’åº(æ•°å­—è¶Šå¤§è¶Šé å‰)" json:"sort"`                                                                  // æŽ’åº(æ•°å­—è¶Šå¤§è¶Šé å‰)
	Status    string         `gorm:"column:status;type:varchar(20);not null;index:idx_banners_station_status,priority:2;default:active;comment:çŠ¶æ€(active/inactive)" json:"status"` // çŠ¶æ€(active/inactive)
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);comment:åˆ›å»ºæ—¶é—´" json:"created_at"`                                  // åˆ›å»ºæ—¶é—´
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);comment:æ›´æ–°æ—¶é—´" json:"updated_at"`                                  // æ›´æ–°æ—¶é—´
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_banners_deleted_at,priority:1;comment:åˆ é™¤æ—¶é—´(è½¯åˆ é™¤)" json:"deleted_at"`                     // åˆ é™¤æ—¶é—´(è½¯åˆ é™¤)

	// Additional fields
	StationName string `gorm:"->;column:station_name" json:"station_name"` // 所属站点名称
}

// TableName Banner's table name
func (*Banner) TableName() string {
	return TableNameBanner
}
