// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMenu = "menus"

// Menu èœå•è¡¨
type Menu struct {
	ID             int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:ä¸»é”®ID" json:"id"`                                                                 // ä¸»é”®ID
	ParentID       int64          `gorm:"column:parent_id;type:bigint unsigned;not null;index:idx_parent_id,priority:1;comment:çˆ¶èœå•IDï¼Œ0è¡¨ç¤ºé¡¶çº§èœå•" json:"parent_id"`                // çˆ¶èœå•IDï¼Œ0è¡¨ç¤ºé¡¶çº§èœå•
	Name           string         `gorm:"column:name;type:varchar(50);not null;comment:èœå•åç§°" json:"name"`                                                                                  // èœå•åç§°
	Path           string         `gorm:"column:path;type:varchar(200);comment:è·¯ç”±è·¯å¾„" json:"path"`                                                                                          // è·¯ç”±è·¯å¾„
	Component      string         `gorm:"column:component;type:varchar(200);comment:å‰ç«¯ç»„ä»¶è·¯å¾„" json:"component"`                                                                          // å‰ç«¯ç»„ä»¶è·¯å¾„
	Icon           string         `gorm:"column:icon;type:varchar(50);comment:å›¾æ ‡åç§°" json:"icon"`                                                                                           // å›¾æ ‡åç§°
	PermissionCode string         `gorm:"column:permission_code;type:varchar(100);index:idx_permission_code,priority:1;comment:æƒé™ç ï¼Œæ ¼å¼: module:resource:action" json:"permission_code"` // æƒé™ç ï¼Œæ ¼å¼: module:resource:action
	Sort           int32          `gorm:"column:sort;type:int;not null;index:idx_sort,priority:1;comment:æŽ’åºå€¼ï¼Œæ•°å­—è¶Šå°è¶Šé å‰" json:"sort"`                                           // æŽ’åºå€¼ï¼Œæ•°å­—è¶Šå°è¶Šé å‰
	Hidden         bool           `gorm:"column:hidden;type:tinyint(1);not null;comment:æ˜¯å¦éšè— 0-æ˜¾ç¤º 1-éšè—" json:"hidden"`                                                             // æ˜¯å¦éšè— 0-æ˜¾ç¤º 1-éšè—
	Status         string         `gorm:"column:status;type:varchar(20);not null;index:idx_status,priority:1;default:active;comment:çŠ¶æ€ active-å¯ç”¨ inactive-ç¦ç”¨" json:"status"`           // çŠ¶æ€ active-å¯ç”¨ inactive-ç¦ç”¨
	CreatedAt      time.Time      `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:åˆ›å»ºæ—¶é—´" json:"created_at"`                                              // åˆ›å»ºæ—¶é—´
	UpdatedAt      time.Time      `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:æ›´æ–°æ—¶é—´" json:"updated_at"`                                              // æ›´æ–°æ—¶é—´
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:è½¯åˆ é™¤æ—¶é—´" json:"deleted_at"`                                                                              // è½¯åˆ é™¤æ—¶é—´
}

// TableName Menu's table name
func (*Menu) TableName() string {
	return TableNameMenu
}
