// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameNews = "news"

// News 新闻资讯表
type News struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键ID" json:"id"` // 主键ID
	StationID int64          `gorm:"column:station_id;type:bigint;index:idx_news_station_id,priority:1" json:"station_id"`
	Title     string         `gorm:"column:title;type:varchar(200);not null" json:"title"`
	Summary   string         `gorm:"column:summary;type:varchar(500)" json:"summary"`
	Content   string         `gorm:"column:content;type:text" json:"content"`
	CoverURL  string         `gorm:"column:cover_url;type:varchar(255)" json:"cover_url"`
	Type      string         `gorm:"column:type;type:varchar(20);index:idx_news_type,priority:1;default:news" json:"type"`
	Status    string         `gorm:"column:status;type:varchar(20);index:idx_news_status,priority:1;default:draft" json:"status"`
	AuthorID  int64          `gorm:"column:author_id;type:bigint;index:idx_news_author_id,priority:1" json:"author_id"`
	PublishAt time.Time      `gorm:"column:publish_at;type:datetime;index:idx_news_publish_at,priority:1" json:"publish_at"`
	ViewCount int64          `gorm:"column:view_count;type:bigint" json:"view_count"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_news_deleted_at,priority:1" json:"deleted_at"`
}

// TableName News's table name
func (*News) TableName() string {
	return TableNameNews
}
