// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameNotification = "notifications"

// Notification 通知表
type Notification struct {
	ID          int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键ID" json:"id"` // 主键ID
	UserID      int64          `gorm:"column:user_id;type:bigint;not null;index:idx_notifications_user_id,priority:1;index:idx_user_id,priority:1" json:"user_id"`
	Title       string         `gorm:"column:title;type:varchar(100);not null" json:"title"`
	Body        string         `gorm:"column:body;type:text" json:"body"`
	Type        string         `gorm:"column:type;type:varchar(20);index:idx_notifications_type,priority:1;index:idx_type,priority:1" json:"type"`
	RelatedID   int64          `gorm:"column:related_id;type:bigint;index:idx_notifications_related_id,priority:1;index:idx_related_id,priority:1" json:"related_id"`
	RelatedType string         `gorm:"column:related_type;type:varchar(20)" json:"related_type"`
	Channel     string         `gorm:"column:channel;type:varchar(20);not null;index:idx_channel,priority:1;index:idx_notifications_channel,priority:1" json:"channel"`
	SendStatus  string         `gorm:"column:send_status;type:varchar(20);index:idx_notifications_send_status,priority:1;index:idx_send_status,priority:1;default:pending" json:"send_status"`
	SentAt      time.Time      `gorm:"column:sent_at;type:datetime" json:"sent_at"`
	IsRead      bool           `gorm:"column:is_read;type:tinyint(1);index:idx_is_read,priority:1;index:idx_notifications_is_read,priority:1" json:"is_read"`
	ReadAt      time.Time      `gorm:"column:read_at;type:datetime" json:"read_at"`
	RetryCount  int64          `gorm:"column:retry_count;type:bigint" json:"retry_count"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_deleted_at,priority:1;index:idx_notifications_deleted_at,priority:1" json:"deleted_at"`
}

// TableName Notification's table name
func (*Notification) TableName() string {
	return TableNameNotification
}
