// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePermission = "permissions"

// Permission æƒé™è¡¨
type Permission struct {
	ID          int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:ä¸»é”®ID" json:"id"`                                                                                           // ä¸»é”®ID
	Code        string         `gorm:"column:code;type:varchar(100);not null;uniqueIndex:uk_code,priority:1;comment:æƒé™ç ï¼Œæ ¼å¼: module:resource:action" json:"code"`                                              // æƒé™ç ï¼Œæ ¼å¼: module:resource:action
	Name        string         `gorm:"column:name;type:varchar(100);not null;comment:æƒé™åç§°" json:"name"`                                                                                                           // æƒé™åç§°
	Description string         `gorm:"column:description;type:varchar(500);comment:æƒé™æè¿°" json:"description"`                                                                                                      // æƒé™æè¿°
	Module      string         `gorm:"column:module;type:varchar(50);not null;index:idx_module,priority:1;comment:æ‰€å±žæ¨¡å—" json:"module"`                                                                            // æ‰€å±žæ¨¡å—
	Type        string         `gorm:"column:type;type:enum('menu','button','resource');not null;index:idx_type,priority:1;default:resource;comment:æƒé™ç±»åž‹: menu-èœå• button-æŒ‰é’® resource-èµ„æº" json:"type"` // æƒé™ç±»åž‹: menu-èœå• button-æŒ‰é’® resource-èµ„æº
	ParentID    int64          `gorm:"column:parent_id;type:bigint unsigned;not null;index:idx_parent_id,priority:1;comment:çˆ¶æƒé™IDï¼Œ0è¡¨ç¤ºé¡¶çº§" json:"parent_id"`                                                // çˆ¶æƒé™IDï¼Œ0è¡¨ç¤ºé¡¶çº§
	APIPath     string         `gorm:"column:api_path;type:varchar(200);index:idx_api,priority:1;comment:APIè·¯å¾„ï¼Œæ”¯æŒé€šé…ç¬¦*" json:"api_path"`                                                                   // APIè·¯å¾„ï¼Œæ”¯æŒé€šé…ç¬¦*
	APIMethod   string         `gorm:"column:api_method;type:varchar(20);index:idx_api,priority:2;comment:HTTPæ–¹æ³•: GET/POST/PUT/DELETE" json:"api_method"`                                                             // HTTPæ–¹æ³•: GET/POST/PUT/DELETE
	IsPublic    bool           `gorm:"column:is_public;type:tinyint(1);not null;comment:æ˜¯å¦å…¬å…±æƒé™ï¼Œ1-æ˜¯ 0-å¦" json:"is_public"`                                                                               // æ˜¯å¦å…¬å…±æƒé™ï¼Œ1-æ˜¯ 0-å¦
	Status      string         `gorm:"column:status;type:varchar(20);not null;index:idx_status,priority:1;default:active;comment:çŠ¶æ€ active-å¯ç”¨ inactive-ç¦ç”¨" json:"status"`                                     // çŠ¶æ€ active-å¯ç”¨ inactive-ç¦ç”¨
	Sort        int32          `gorm:"column:sort;type:int;not null;comment:æŽ’åºå€¼" json:"sort"`                                                                                                                       // æŽ’åºå€¼
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:åˆ›å»ºæ—¶é—´" json:"created_at"`                                                                        // åˆ›å»ºæ—¶é—´
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:æ›´æ–°æ—¶é—´" json:"updated_at"`                                                                        // æ›´æ–°æ—¶é—´
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;uniqueIndex:uk_code,priority:2;comment:è½¯åˆ é™¤æ—¶é—´" json:"deleted_at"`                                                                         // è½¯åˆ é™¤æ—¶é—´
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
