// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameReport = "reports"

// Report ç»Ÿè®¡æŠ¥è¡¨
type Report struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;index:idx_reports_created_at,priority:1;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;index:idx_reports_deleted_at,priority:1" json:"deleted_at"`
	Name      string         `gorm:"column:name;type:varchar(255);not null;comment:æŠ¥è¡¨åç§°" json:"name"`                                                                        // æŠ¥è¡¨åç§°
	Type      string         `gorm:"column:type;type:varchar(32);not null;index:idx_reports_type,priority:1;comment:æŠ¥è¡¨ç±»åž‹ï¼šservice/performance/request/station" json:"type"` // æŠ¥è¡¨ç±»åž‹ï¼šservice/performance/request/station
	Format    string         `gorm:"column:format;type:varchar(16);not null;comment:æ–‡ä»¶æ ¼å¼ï¼šxlsx/csv" json:"format"`                                                          // æ–‡ä»¶æ ¼å¼ï¼šxlsx/csv
	FilePath  string         `gorm:"column:file_path;type:varchar(512);not null;comment:æ–‡ä»¶å­˜å‚¨è·¯å¾„" json:"file_path"`                                                        // æ–‡ä»¶å­˜å‚¨è·¯å¾„
	FileSize  int64          `gorm:"column:file_size;type:bigint;not null;comment:æ–‡ä»¶å¤§å°ï¼ˆå­—èŠ‚ï¼‰" json:"file_size"`                                                        // æ–‡ä»¶å¤§å°ï¼ˆå­—èŠ‚ï¼‰
	StationID int64          `gorm:"column:station_id;type:bigint;index:idx_reports_station_id,priority:1;comment:ç«™ç‚¹IDï¼ŒNULLè¡¨ç¤ºå…¨å±€" json:"station_id"`                    // ç«™ç‚¹IDï¼ŒNULLè¡¨ç¤ºå…¨å±€
	StartDate time.Time      `gorm:"column:start_date;type:date;not null;comment:ç»Ÿè®¡å¼€å§‹æ—¥æœŸ" json:"start_date"`                                                              // ç»Ÿè®¡å¼€å§‹æ—¥æœŸ
	EndDate   time.Time      `gorm:"column:end_date;type:date;not null;comment:ç»Ÿè®¡ç»“æŸæ—¥æœŸ" json:"end_date"`                                                                  // ç»Ÿè®¡ç»“æŸæ—¥æœŸ
	CreatedBy int64          `gorm:"column:created_by;type:bigint;not null;index:idx_reports_created_by,priority:1;comment:åˆ›å»ºäººID" json:"created_by"`                           // åˆ›å»ºäººID
}

// TableName Report's table name
func (*Report) TableName() string {
	return TableNameReport
}
