// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRolePermission = "role_permissions"

// RolePermission mapped from table <role_permissions>
type RolePermission struct {
	ID           int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:ä¸»é”®ID" json:"id"`                                                                         // ä¸»é”®ID
	RoleID       int64     `gorm:"column:role_id;type:bigint unsigned;not null;uniqueIndex:uk_role_perm,priority:1;index:idx_role_id,priority:1;comment:è§’è‰²ID" json:"role_id"`                   // è§’è‰²ID
	PermissionID int64     `gorm:"column:permission_id;type:bigint unsigned;not null;uniqueIndex:uk_role_perm,priority:2;index:idx_permission_id,priority:1;comment:æƒé™ID" json:"permission_id"` // æƒé™ID
	CreatedAt    time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:åˆ›å»ºæ—¶é—´" json:"created_at"`                                                      // åˆ›å»ºæ—¶é—´
}

// TableName RolePermission's table name
func (*RolePermission) TableName() string {
	return TableNameRolePermission
}
