// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	ID          int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:ä¸»é”®ID" json:"id"`                                                       // ä¸»é”®ID
	Code        string         `gorm:"column:code;type:varchar(50);not null;uniqueIndex:uk_code,priority:1;comment:è§’è‰²ç¼–ç ï¼Œå¦‚ admin, staff" json:"code"`                      // è§’è‰²ç¼–ç ï¼Œå¦‚ admin, staff
	Name        string         `gorm:"column:name;type:varchar(100);not null;comment:è§’è‰²åç§°" json:"name"`                                                                       // è§’è‰²åç§°
	Description string         `gorm:"column:description;type:varchar(500);comment:è§’è‰²æè¿°" json:"description"`                                                                  // è§’è‰²æè¿°
	IsSystem    bool           `gorm:"column:is_system;type:tinyint(1);not null;comment:æ˜¯å¦ç³»ç»Ÿå†…ç½®è§’è‰²ï¼Œ1-æ˜¯ 0-å¦" json:"is_system"`                                     // æ˜¯å¦ç³»ç»Ÿå†…ç½®è§’è‰²ï¼Œ1-æ˜¯ 0-å¦
	Status      string         `gorm:"column:status;type:varchar(20);not null;index:idx_status,priority:1;default:active;comment:çŠ¶æ€ active-å¯ç”¨ inactive-ç¦ç”¨" json:"status"` // çŠ¶æ€ active-å¯ç”¨ inactive-ç¦ç”¨
	Sort        int32          `gorm:"column:sort;type:int;not null;comment:æŽ’åºå€¼" json:"sort"`                                                                                   // æŽ’åºå€¼
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:åˆ›å»ºæ—¶é—´" json:"created_at"`                                    // åˆ›å»ºæ—¶é—´
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:æ›´æ–°æ—¶é—´" json:"updated_at"`                                    // æ›´æ–°æ—¶é—´
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;uniqueIndex:uk_code,priority:2;comment:è½¯åˆ é™¤æ—¶é—´" json:"deleted_at"`                                     // è½¯åˆ é™¤æ—¶é—´
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
