// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameServiceStation = "service_stations"

// ServiceStation 服务站点表
type ServiceStation struct {
	ID          int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键ID" json:"id"` // 主键ID
	Name        string         `gorm:"column:name;type:varchar(100);not null" json:"name"`
	Code        string         `gorm:"column:code;type:varchar(50);uniqueIndex:idx_service_stations_code,priority:1" json:"code"`
	Address     string         `gorm:"column:address;type:varchar(200)" json:"address"`
	Phone       string         `gorm:"column:phone;type:varchar(20)" json:"phone"`
	Latitude    float64        `gorm:"column:latitude;type:decimal(10,7)" json:"latitude"`
	Longitude   float64        `gorm:"column:longitude;type:decimal(10,7)" json:"longitude"`
	ServiceArea string         `gorm:"column:service_area;type:varchar(200)" json:"service_area"`
	Capacity    int64          `gorm:"column:capacity;type:bigint;default:10" json:"capacity"`
	WorkHours   string         `gorm:"column:work_hours;type:varchar(100)" json:"work_hours"`
	Status      string         `gorm:"column:status;type:varchar(20);index:idx_service_stations_status,priority:1;index:idx_status,priority:1;default:active" json:"status"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_deleted_at,priority:1;index:idx_service_stations_deleted_at,priority:1" json:"deleted_at"`
}

// TableName ServiceStation's table name
func (*ServiceStation) TableName() string {
	return TableNameServiceStation
}
