// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameServiceZone = "service_zones"

// ServiceZone 服务围栏表
type ServiceZone struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键ID" json:"id"` // 主键ID
	StationID int64          `gorm:"column:station_id;type:bigint;not null;index:idx_service_zones_station_id,priority:1;index:idx_station_id,priority:1" json:"station_id"`
	Name      string         `gorm:"column:name;type:varchar(100);not null" json:"name"`
	Points    string         `gorm:"column:points;type:json;not null" json:"points"`
	Priority  int64          `gorm:"column:priority;type:bigint" json:"priority"`
	Status    string         `gorm:"column:status;type:varchar(20);index:idx_service_zones_status,priority:1;index:idx_status,priority:1;default:active" json:"status"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_deleted_at,priority:1;index:idx_service_zones_deleted_at,priority:1" json:"deleted_at"`
}

// TableName ServiceZone's table name
func (*ServiceZone) TableName() string {
	return TableNameServiceZone
}
