// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTaskAssignment = "task_assignments"

// TaskAssignment 任务分配表
type TaskAssignment struct {
	ID          int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键ID" json:"id"` // 主键ID
	RequestID   int64          `gorm:"column:request_id;type:bigint;not null;index:idx_request_id,priority:1;index:idx_task_assignments_request_id,priority:1" json:"request_id"`
	StationID   int64          `gorm:"column:station_id;type:bigint;not null;index:idx_station_id,priority:1;index:idx_task_assignments_station_id,priority:1" json:"station_id"`
	StaffID     int64          `gorm:"column:staff_id;type:bigint;index:idx_staff_id,priority:1;index:idx_task_assignments_staff_id,priority:1" json:"staff_id"`
	Status      string         `gorm:"column:status;type:varchar(20);index:idx_status,priority:1;index:idx_task_assignments_status,priority:1;default:dispatched" json:"status"`
	ClaimedAt   time.Time      `gorm:"column:claimed_at;type:datetime" json:"claimed_at"`
	CompletedAt time.Time      `gorm:"column:completed_at;type:datetime" json:"completed_at"`
	Rating      int64          `gorm:"column:rating;type:bigint" json:"rating"`
	Feedback    string         `gorm:"column:feedback;type:text" json:"feedback"`
	StaffNotes  string         `gorm:"column:staff_notes;type:text" json:"staff_notes"`
	Images      string         `gorm:"column:images;type:json" json:"images"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_deleted_at,priority:1;index:idx_task_assignments_deleted_at,priority:1" json:"deleted_at"`
}

// TableName TaskAssignment's table name
func (*TaskAssignment) TableName() string {
	return TableNameTaskAssignment
}
