// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTaskHistory = "task_histories"

// TaskHistory 任务历史表
type TaskHistory struct {
	ID            int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键ID" json:"id"` // 主键ID
	TaskID        int64          `gorm:"column:task_id;type:bigint;not null;index:idx_task_histories_task_id,priority:1;index:idx_task_id,priority:1" json:"task_id"`
	RequestID     int64          `gorm:"column:request_id;type:bigint;not null;index:idx_request_id,priority:1;index:idx_task_histories_request_id,priority:1" json:"request_id"`
	Action        string         `gorm:"column:action;type:varchar(20);not null" json:"action"`
	OperatorID    int64          `gorm:"column:operator_id;type:bigint;not null;index:idx_operator_id,priority:1;index:idx_task_histories_operator_id,priority:1" json:"operator_id"`
	FromStaffID   int64          `gorm:"column:from_staff_id;type:bigint;index:idx_from_staff_id,priority:1;index:idx_task_histories_from_staff_id,priority:1" json:"from_staff_id"`
	ToStaffID     int64          `gorm:"column:to_staff_id;type:bigint;index:idx_task_histories_to_staff_id,priority:1;index:idx_to_staff_id,priority:1" json:"to_staff_id"`
	FromStationID int64          `gorm:"column:from_station_id;type:bigint;index:idx_from_station_id,priority:1;index:idx_task_histories_from_station_id,priority:1" json:"from_station_id"`
	ToStationID   int64          `gorm:"column:to_station_id;type:bigint;index:idx_task_histories_to_station_id,priority:1;index:idx_to_station_id,priority:1" json:"to_station_id"`
	StatusBefore  string         `gorm:"column:status_before;type:varchar(20)" json:"status_before"`
	StatusAfter   string         `gorm:"column:status_after;type:varchar(20)" json:"status_after"`
	Remark        string         `gorm:"column:remark;type:text" json:"remark"`
	CreatedAt     time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_deleted_at,priority:1;index:idx_task_histories_deleted_at,priority:1" json:"deleted_at"`
}

// TableName TaskHistory's table name
func (*TaskHistory) TableName() string {
	return TableNameTaskHistory
}
