// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserIdentity = "user_identities"

// UserIdentity 用户身份表
type UserIdentity struct {
	ID           int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                                                                                                                         // 主键ID
	UserID       int64          `gorm:"column:user_id;type:bigint;not null;uniqueIndex:uk_user_identity,priority:1;index:idx_ui_user_id,priority:1;comment:用户ID" json:"user_id"`                                                                            // 用户ID
	IdentityType string         `gorm:"column:identity_type;type:varchar(20);not null;uniqueIndex:uk_user_identity,priority:2;index:idx_ui_identity_type,priority:1;comment:身份类型: B端(admin/station_manager/staff) C端(elderly/family)" json:"identity_type"` // 身份类型: B端(admin/station_manager/staff) C端(elderly/family)
	IsPrimary    bool           `gorm:"column:is_primary;type:tinyint(1);not null;comment:是否主身份(每用户有且仅有一个)" json:"is_primary"`                                                                                                                              // 是否主身份(每用户有且仅有一个)
	StationID    int64          `gorm:"column:station_id;type:bigint;index:idx_ui_station_id,priority:1;comment:所属服务站ID(仅B端身份)" json:"station_id"`                                                                                                          // 所属服务站ID(仅B端身份)
	Status       string         `gorm:"column:status;type:varchar(20);not null;index:idx_ui_status,priority:1;default:active;comment:身份状态(active/inactive)" json:"status"`                                                                                  // 身份状态(active/inactive)
	GrantedAt    time.Time      `gorm:"column:granted_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:授予时间" json:"granted_at"`                                                                                                                  // 授予时间
	GrantedBy    int64          `gorm:"column:granted_by;type:bigint;comment:授予人ID" json:"granted_by"`                                                                                                                                                      // 授予人ID
	RevokedAt    time.Time      `gorm:"column:revoked_at;type:datetime;comment:撤销时间" json:"revoked_at"`                                                                                                                                                     // 撤销时间
	CreatedAt    time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                                                                                                  // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                                                                                                  // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;uniqueIndex:uk_user_identity,priority:3;index:idx_ui_deleted_at,priority:1;comment:删除时间(软删除)" json:"deleted_at"`                                                                     // 删除时间(软删除)
}

// TableName UserIdentity's table name
func (*UserIdentity) TableName() string {
	return TableNameUserIdentity
}
