// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User 用户表
type User struct {
	ID           int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键ID" json:"id"` // 主键ID
	Phone        string         `gorm:"column:phone;type:varchar(20);not null;uniqueIndex:idx_users_phone,priority:1" json:"phone"`
	PasswordHash string         `gorm:"column:password_hash;type:varchar(255);not null" json:"password_hash"`
	Name         string         `gorm:"column:name;type:varchar(50)" json:"name"`
	Email        string         `gorm:"column:email;type:varchar(100);index:idx_users_email,priority:1" json:"email"`
	Avatar       string         `gorm:"column:avatar;type:varchar(255)" json:"avatar"`
	Gender       string         `gorm:"column:gender;type:varchar(10)" json:"gender"`
	BirthDate    time.Time      `gorm:"column:birth_date;type:date" json:"birth_date"`
	IDCard       string         `gorm:"column:id_card;type:varchar(18);index:idx_id_card,priority:1;index:idx_users_id_card,priority:1" json:"id_card"`
	IDCardHmac   string         `gorm:"column:id_card_hmac;type:varchar(64);comment:身份证号HMAC摘要" json:"id_card_hmac"`
	StationID    int64          `gorm:"column:station_id;type:bigint;index:idx_station_id,priority:1;index:idx_users_station_id,priority:1" json:"station_id"`
	Status       string         `gorm:"column:status;type:varchar(20);index:idx_status,priority:1;index:idx_users_status,priority:1;default:active" json:"status"`
	CreatedAt    time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_deleted_at,priority:1;index:idx_users_deleted_at,priority:1" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
