// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"community-elderly-care-platform/internal/dao/model"
)

func newCustomerProfile(db *gorm.DB, opts ...gen.DOOption) customerProfile {
	_customerProfile := customerProfile{}

	_customerProfile.customerProfileDo.UseDB(db, opts...)
	_customerProfile.customerProfileDo.UseModel(&model.CustomerProfile{})

	tableName := _customerProfile.customerProfileDo.TableName()
	_customerProfile.ALL = field.NewAsterisk(tableName)
	_customerProfile.ID = field.NewInt64(tableName, "id")
	_customerProfile.UserID = field.NewInt64(tableName, "user_id")
	_customerProfile.IDCard = field.NewString(tableName, "id_card")
	_customerProfile.Gender = field.NewString(tableName, "gender")
	_customerProfile.BirthDate = field.NewTime(tableName, "birth_date")
	_customerProfile.Address = field.NewString(tableName, "address")
	_customerProfile.CustomerType = field.NewString(tableName, "customer_type")
	_customerProfile.HealthStatus = field.NewString(tableName, "health_status")
	_customerProfile.DisabilityLevel = field.NewString(tableName, "disability_level")
	_customerProfile.MedicalHistory = field.NewString(tableName, "medical_history")
	_customerProfile.SpecialNeeds = field.NewString(tableName, "special_needs")
	_customerProfile.EmergencyContact = field.NewString(tableName, "emergency_contact")
	_customerProfile.CreatedAt = field.NewTime(tableName, "created_at")
	_customerProfile.UpdatedAt = field.NewTime(tableName, "updated_at")

	_customerProfile.fillFieldMap()

	return _customerProfile
}

// customerProfile å®¢æˆ·æ¡£æ¡ˆè¡¨ï¼ˆæœåŠ¡å¯¹è±¡ï¼‰
type customerProfile struct {
	customerProfileDo

	ALL              field.Asterisk
	ID               field.Int64
	UserID           field.Int64  // å…³è”ç”¨æˆ·ID
	IDCard           field.String // èº«ä»½è¯å·
	Gender           field.String // æ€§åˆ«
	BirthDate        field.Time   // å‡ºç”Ÿæ—¥æœŸ
	Address          field.String // å±…ä½åœ°å€
	CustomerType     field.String // å®¢æˆ·ç±»åž‹ï¼šelderly/disabled/pregnant/child/other
	HealthStatus     field.String // å¥åº·çŠ¶å†µ
	DisabilityLevel  field.String // å¤±èƒ½ç­‰çº§ï¼šè‡ªç†/è½»åº¦/ä¸­åº¦/é‡åº¦
	MedicalHistory   field.String // ç—…å²
	SpecialNeeds     field.String // ç‰¹æ®Šéœ€æ±‚
	EmergencyContact field.String // ç´§æ€¥è”ç³»äºº {"name":"","phone":"","relation":""}
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (c customerProfile) Table(newTableName string) *customerProfile {
	c.customerProfileDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c customerProfile) As(alias string) *customerProfile {
	c.customerProfileDo.DO = *(c.customerProfileDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *customerProfile) updateTableName(table string) *customerProfile {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.UserID = field.NewInt64(table, "user_id")
	c.IDCard = field.NewString(table, "id_card")
	c.Gender = field.NewString(table, "gender")
	c.BirthDate = field.NewTime(table, "birth_date")
	c.Address = field.NewString(table, "address")
	c.CustomerType = field.NewString(table, "customer_type")
	c.HealthStatus = field.NewString(table, "health_status")
	c.DisabilityLevel = field.NewString(table, "disability_level")
	c.MedicalHistory = field.NewString(table, "medical_history")
	c.SpecialNeeds = field.NewString(table, "special_needs")
	c.EmergencyContact = field.NewString(table, "emergency_contact")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *customerProfile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *customerProfile) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 14)
	c.fieldMap["id"] = c.ID
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["id_card"] = c.IDCard
	c.fieldMap["gender"] = c.Gender
	c.fieldMap["birth_date"] = c.BirthDate
	c.fieldMap["address"] = c.Address
	c.fieldMap["customer_type"] = c.CustomerType
	c.fieldMap["health_status"] = c.HealthStatus
	c.fieldMap["disability_level"] = c.DisabilityLevel
	c.fieldMap["medical_history"] = c.MedicalHistory
	c.fieldMap["special_needs"] = c.SpecialNeeds
	c.fieldMap["emergency_contact"] = c.EmergencyContact
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c customerProfile) clone(db *gorm.DB) customerProfile {
	c.customerProfileDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c customerProfile) replaceDB(db *gorm.DB) customerProfile {
	c.customerProfileDo.ReplaceDB(db)
	return c
}

type customerProfileDo struct{ gen.DO }

type ICustomerProfileDo interface {
	gen.SubQuery
	Debug() ICustomerProfileDo
	WithContext(ctx context.Context) ICustomerProfileDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICustomerProfileDo
	WriteDB() ICustomerProfileDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICustomerProfileDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICustomerProfileDo
	Not(conds ...gen.Condition) ICustomerProfileDo
	Or(conds ...gen.Condition) ICustomerProfileDo
	Select(conds ...field.Expr) ICustomerProfileDo
	Where(conds ...gen.Condition) ICustomerProfileDo
	Order(conds ...field.Expr) ICustomerProfileDo
	Distinct(cols ...field.Expr) ICustomerProfileDo
	Omit(cols ...field.Expr) ICustomerProfileDo
	Join(table schema.Tabler, on ...field.Expr) ICustomerProfileDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICustomerProfileDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICustomerProfileDo
	Group(cols ...field.Expr) ICustomerProfileDo
	Having(conds ...gen.Condition) ICustomerProfileDo
	Limit(limit int) ICustomerProfileDo
	Offset(offset int) ICustomerProfileDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICustomerProfileDo
	Unscoped() ICustomerProfileDo
	Create(values ...*model.CustomerProfile) error
	CreateInBatches(values []*model.CustomerProfile, batchSize int) error
	Save(values ...*model.CustomerProfile) error
	First() (*model.CustomerProfile, error)
	Take() (*model.CustomerProfile, error)
	Last() (*model.CustomerProfile, error)
	Find() ([]*model.CustomerProfile, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CustomerProfile, err error)
	FindInBatches(result *[]*model.CustomerProfile, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CustomerProfile) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICustomerProfileDo
	Assign(attrs ...field.AssignExpr) ICustomerProfileDo
	Joins(fields ...field.RelationField) ICustomerProfileDo
	Preload(fields ...field.RelationField) ICustomerProfileDo
	FirstOrInit() (*model.CustomerProfile, error)
	FirstOrCreate() (*model.CustomerProfile, error)
	FindByPage(offset int, limit int) (result []*model.CustomerProfile, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICustomerProfileDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c customerProfileDo) Debug() ICustomerProfileDo {
	return c.withDO(c.DO.Debug())
}

func (c customerProfileDo) WithContext(ctx context.Context) ICustomerProfileDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c customerProfileDo) ReadDB() ICustomerProfileDo {
	return c.Clauses(dbresolver.Read)
}

func (c customerProfileDo) WriteDB() ICustomerProfileDo {
	return c.Clauses(dbresolver.Write)
}

func (c customerProfileDo) Session(config *gorm.Session) ICustomerProfileDo {
	return c.withDO(c.DO.Session(config))
}

func (c customerProfileDo) Clauses(conds ...clause.Expression) ICustomerProfileDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c customerProfileDo) Returning(value interface{}, columns ...string) ICustomerProfileDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c customerProfileDo) Not(conds ...gen.Condition) ICustomerProfileDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c customerProfileDo) Or(conds ...gen.Condition) ICustomerProfileDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c customerProfileDo) Select(conds ...field.Expr) ICustomerProfileDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c customerProfileDo) Where(conds ...gen.Condition) ICustomerProfileDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c customerProfileDo) Order(conds ...field.Expr) ICustomerProfileDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c customerProfileDo) Distinct(cols ...field.Expr) ICustomerProfileDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c customerProfileDo) Omit(cols ...field.Expr) ICustomerProfileDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c customerProfileDo) Join(table schema.Tabler, on ...field.Expr) ICustomerProfileDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c customerProfileDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICustomerProfileDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c customerProfileDo) RightJoin(table schema.Tabler, on ...field.Expr) ICustomerProfileDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c customerProfileDo) Group(cols ...field.Expr) ICustomerProfileDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c customerProfileDo) Having(conds ...gen.Condition) ICustomerProfileDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c customerProfileDo) Limit(limit int) ICustomerProfileDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c customerProfileDo) Offset(offset int) ICustomerProfileDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c customerProfileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICustomerProfileDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c customerProfileDo) Unscoped() ICustomerProfileDo {
	return c.withDO(c.DO.Unscoped())
}

func (c customerProfileDo) Create(values ...*model.CustomerProfile) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c customerProfileDo) CreateInBatches(values []*model.CustomerProfile, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c customerProfileDo) Save(values ...*model.CustomerProfile) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c customerProfileDo) First() (*model.CustomerProfile, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CustomerProfile), nil
	}
}

func (c customerProfileDo) Take() (*model.CustomerProfile, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CustomerProfile), nil
	}
}

func (c customerProfileDo) Last() (*model.CustomerProfile, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CustomerProfile), nil
	}
}

func (c customerProfileDo) Find() ([]*model.CustomerProfile, error) {
	result, err := c.DO.Find()
	return result.([]*model.CustomerProfile), err
}

func (c customerProfileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CustomerProfile, err error) {
	buf := make([]*model.CustomerProfile, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c customerProfileDo) FindInBatches(result *[]*model.CustomerProfile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c customerProfileDo) Attrs(attrs ...field.AssignExpr) ICustomerProfileDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c customerProfileDo) Assign(attrs ...field.AssignExpr) ICustomerProfileDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c customerProfileDo) Joins(fields ...field.RelationField) ICustomerProfileDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c customerProfileDo) Preload(fields ...field.RelationField) ICustomerProfileDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c customerProfileDo) FirstOrInit() (*model.CustomerProfile, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CustomerProfile), nil
	}
}

func (c customerProfileDo) FirstOrCreate() (*model.CustomerProfile, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CustomerProfile), nil
	}
}

func (c customerProfileDo) FindByPage(offset int, limit int) (result []*model.CustomerProfile, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c customerProfileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c customerProfileDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c customerProfileDo) Delete(models ...*model.CustomerProfile) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *customerProfileDo) withDO(do gen.Dao) *customerProfileDo {
	c.DO = *do.(*gen.DO)
	return c
}
