// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	Banner          *banner
	CustomerProfile *customerProfile
	Menu            *menu
	News            *news
	Notification    *notification
	Permission      *permission
	Report          *report
	Role            *role
	RolePermission  *rolePermission
	SchemaMigration *schemaMigration
	ServiceRequest  *serviceRequest
	ServiceStation  *serviceStation
	ServiceZone     *serviceZone
	TaskAssignment  *taskAssignment
	TaskHistory     *taskHistory
	User            *user
	UserIdentity    *userIdentity
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Banner = &Q.Banner
	CustomerProfile = &Q.CustomerProfile
	Menu = &Q.Menu
	News = &Q.News
	Notification = &Q.Notification
	Permission = &Q.Permission
	Report = &Q.Report
	Role = &Q.Role
	RolePermission = &Q.RolePermission
	SchemaMigration = &Q.SchemaMigration
	ServiceRequest = &Q.ServiceRequest
	ServiceStation = &Q.ServiceStation
	ServiceZone = &Q.ServiceZone
	TaskAssignment = &Q.TaskAssignment
	TaskHistory = &Q.TaskHistory
	User = &Q.User
	UserIdentity = &Q.UserIdentity
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		Banner:          newBanner(db, opts...),
		CustomerProfile: newCustomerProfile(db, opts...),
		Menu:            newMenu(db, opts...),
		News:            newNews(db, opts...),
		Notification:    newNotification(db, opts...),
		Permission:      newPermission(db, opts...),
		Report:          newReport(db, opts...),
		Role:            newRole(db, opts...),
		RolePermission:  newRolePermission(db, opts...),
		SchemaMigration: newSchemaMigration(db, opts...),
		ServiceRequest:  newServiceRequest(db, opts...),
		ServiceStation:  newServiceStation(db, opts...),
		ServiceZone:     newServiceZone(db, opts...),
		TaskAssignment:  newTaskAssignment(db, opts...),
		TaskHistory:     newTaskHistory(db, opts...),
		User:            newUser(db, opts...),
		UserIdentity:    newUserIdentity(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Banner          banner
	CustomerProfile customerProfile
	Menu            menu
	News            news
	Notification    notification
	Permission      permission
	Report          report
	Role            role
	RolePermission  rolePermission
	SchemaMigration schemaMigration
	ServiceRequest  serviceRequest
	ServiceStation  serviceStation
	ServiceZone     serviceZone
	TaskAssignment  taskAssignment
	TaskHistory     taskHistory
	User            user
	UserIdentity    userIdentity
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Banner:          q.Banner.clone(db),
		CustomerProfile: q.CustomerProfile.clone(db),
		Menu:            q.Menu.clone(db),
		News:            q.News.clone(db),
		Notification:    q.Notification.clone(db),
		Permission:      q.Permission.clone(db),
		Report:          q.Report.clone(db),
		Role:            q.Role.clone(db),
		RolePermission:  q.RolePermission.clone(db),
		SchemaMigration: q.SchemaMigration.clone(db),
		ServiceRequest:  q.ServiceRequest.clone(db),
		ServiceStation:  q.ServiceStation.clone(db),
		ServiceZone:     q.ServiceZone.clone(db),
		TaskAssignment:  q.TaskAssignment.clone(db),
		TaskHistory:     q.TaskHistory.clone(db),
		User:            q.User.clone(db),
		UserIdentity:    q.UserIdentity.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Banner:          q.Banner.replaceDB(db),
		CustomerProfile: q.CustomerProfile.replaceDB(db),
		Menu:            q.Menu.replaceDB(db),
		News:            q.News.replaceDB(db),
		Notification:    q.Notification.replaceDB(db),
		Permission:      q.Permission.replaceDB(db),
		Report:          q.Report.replaceDB(db),
		Role:            q.Role.replaceDB(db),
		RolePermission:  q.RolePermission.replaceDB(db),
		SchemaMigration: q.SchemaMigration.replaceDB(db),
		ServiceRequest:  q.ServiceRequest.replaceDB(db),
		ServiceStation:  q.ServiceStation.replaceDB(db),
		ServiceZone:     q.ServiceZone.replaceDB(db),
		TaskAssignment:  q.TaskAssignment.replaceDB(db),
		TaskHistory:     q.TaskHistory.replaceDB(db),
		User:            q.User.replaceDB(db),
		UserIdentity:    q.UserIdentity.replaceDB(db),
	}
}

type queryCtx struct {
	Banner          IBannerDo
	CustomerProfile ICustomerProfileDo
	Menu            IMenuDo
	News            INewsDo
	Notification    INotificationDo
	Permission      IPermissionDo
	Report          IReportDo
	Role            IRoleDo
	RolePermission  IRolePermissionDo
	SchemaMigration ISchemaMigrationDo
	ServiceRequest  IServiceRequestDo
	ServiceStation  IServiceStationDo
	ServiceZone     IServiceZoneDo
	TaskAssignment  ITaskAssignmentDo
	TaskHistory     ITaskHistoryDo
	User            IUserDo
	UserIdentity    IUserIdentityDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Banner:          q.Banner.WithContext(ctx),
		CustomerProfile: q.CustomerProfile.WithContext(ctx),
		Menu:            q.Menu.WithContext(ctx),
		News:            q.News.WithContext(ctx),
		Notification:    q.Notification.WithContext(ctx),
		Permission:      q.Permission.WithContext(ctx),
		Report:          q.Report.WithContext(ctx),
		Role:            q.Role.WithContext(ctx),
		RolePermission:  q.RolePermission.WithContext(ctx),
		SchemaMigration: q.SchemaMigration.WithContext(ctx),
		ServiceRequest:  q.ServiceRequest.WithContext(ctx),
		ServiceStation:  q.ServiceStation.WithContext(ctx),
		ServiceZone:     q.ServiceZone.WithContext(ctx),
		TaskAssignment:  q.TaskAssignment.WithContext(ctx),
		TaskHistory:     q.TaskHistory.WithContext(ctx),
		User:            q.User.WithContext(ctx),
		UserIdentity:    q.UserIdentity.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
