// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"community-elderly-care-platform/internal/dao/model"
)

func newServiceZone(db *gorm.DB, opts ...gen.DOOption) serviceZone {
	_serviceZone := serviceZone{}

	_serviceZone.serviceZoneDo.UseDB(db, opts...)
	_serviceZone.serviceZoneDo.UseModel(&model.ServiceZone{})

	tableName := _serviceZone.serviceZoneDo.TableName()
	_serviceZone.ALL = field.NewAsterisk(tableName)
	_serviceZone.ID = field.NewInt64(tableName, "id")
	_serviceZone.StationID = field.NewInt64(tableName, "station_id")
	_serviceZone.Name = field.NewString(tableName, "name")
	_serviceZone.Points = field.NewString(tableName, "points")
	_serviceZone.Priority = field.NewInt64(tableName, "priority")
	_serviceZone.Status = field.NewString(tableName, "status")
	_serviceZone.CreatedAt = field.NewTime(tableName, "created_at")
	_serviceZone.UpdatedAt = field.NewTime(tableName, "updated_at")
	_serviceZone.DeletedAt = field.NewField(tableName, "deleted_at")

	_serviceZone.fillFieldMap()

	return _serviceZone
}

// serviceZone 服务围栏表
type serviceZone struct {
	serviceZoneDo

	ALL       field.Asterisk
	ID        field.Int64 // 主键ID
	StationID field.Int64
	Name      field.String
	Points    field.String
	Priority  field.Int64
	Status    field.String
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field

	fieldMap map[string]field.Expr
}

func (s serviceZone) Table(newTableName string) *serviceZone {
	s.serviceZoneDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s serviceZone) As(alias string) *serviceZone {
	s.serviceZoneDo.DO = *(s.serviceZoneDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *serviceZone) updateTableName(table string) *serviceZone {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.StationID = field.NewInt64(table, "station_id")
	s.Name = field.NewString(table, "name")
	s.Points = field.NewString(table, "points")
	s.Priority = field.NewInt64(table, "priority")
	s.Status = field.NewString(table, "status")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *serviceZone) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *serviceZone) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.ID
	s.fieldMap["station_id"] = s.StationID
	s.fieldMap["name"] = s.Name
	s.fieldMap["points"] = s.Points
	s.fieldMap["priority"] = s.Priority
	s.fieldMap["status"] = s.Status
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s serviceZone) clone(db *gorm.DB) serviceZone {
	s.serviceZoneDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s serviceZone) replaceDB(db *gorm.DB) serviceZone {
	s.serviceZoneDo.ReplaceDB(db)
	return s
}

type serviceZoneDo struct{ gen.DO }

type IServiceZoneDo interface {
	gen.SubQuery
	Debug() IServiceZoneDo
	WithContext(ctx context.Context) IServiceZoneDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IServiceZoneDo
	WriteDB() IServiceZoneDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IServiceZoneDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IServiceZoneDo
	Not(conds ...gen.Condition) IServiceZoneDo
	Or(conds ...gen.Condition) IServiceZoneDo
	Select(conds ...field.Expr) IServiceZoneDo
	Where(conds ...gen.Condition) IServiceZoneDo
	Order(conds ...field.Expr) IServiceZoneDo
	Distinct(cols ...field.Expr) IServiceZoneDo
	Omit(cols ...field.Expr) IServiceZoneDo
	Join(table schema.Tabler, on ...field.Expr) IServiceZoneDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IServiceZoneDo
	RightJoin(table schema.Tabler, on ...field.Expr) IServiceZoneDo
	Group(cols ...field.Expr) IServiceZoneDo
	Having(conds ...gen.Condition) IServiceZoneDo
	Limit(limit int) IServiceZoneDo
	Offset(offset int) IServiceZoneDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IServiceZoneDo
	Unscoped() IServiceZoneDo
	Create(values ...*model.ServiceZone) error
	CreateInBatches(values []*model.ServiceZone, batchSize int) error
	Save(values ...*model.ServiceZone) error
	First() (*model.ServiceZone, error)
	Take() (*model.ServiceZone, error)
	Last() (*model.ServiceZone, error)
	Find() ([]*model.ServiceZone, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ServiceZone, err error)
	FindInBatches(result *[]*model.ServiceZone, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ServiceZone) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IServiceZoneDo
	Assign(attrs ...field.AssignExpr) IServiceZoneDo
	Joins(fields ...field.RelationField) IServiceZoneDo
	Preload(fields ...field.RelationField) IServiceZoneDo
	FirstOrInit() (*model.ServiceZone, error)
	FirstOrCreate() (*model.ServiceZone, error)
	FindByPage(offset int, limit int) (result []*model.ServiceZone, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IServiceZoneDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s serviceZoneDo) Debug() IServiceZoneDo {
	return s.withDO(s.DO.Debug())
}

func (s serviceZoneDo) WithContext(ctx context.Context) IServiceZoneDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s serviceZoneDo) ReadDB() IServiceZoneDo {
	return s.Clauses(dbresolver.Read)
}

func (s serviceZoneDo) WriteDB() IServiceZoneDo {
	return s.Clauses(dbresolver.Write)
}

func (s serviceZoneDo) Session(config *gorm.Session) IServiceZoneDo {
	return s.withDO(s.DO.Session(config))
}

func (s serviceZoneDo) Clauses(conds ...clause.Expression) IServiceZoneDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s serviceZoneDo) Returning(value interface{}, columns ...string) IServiceZoneDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s serviceZoneDo) Not(conds ...gen.Condition) IServiceZoneDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s serviceZoneDo) Or(conds ...gen.Condition) IServiceZoneDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s serviceZoneDo) Select(conds ...field.Expr) IServiceZoneDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s serviceZoneDo) Where(conds ...gen.Condition) IServiceZoneDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s serviceZoneDo) Order(conds ...field.Expr) IServiceZoneDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s serviceZoneDo) Distinct(cols ...field.Expr) IServiceZoneDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s serviceZoneDo) Omit(cols ...field.Expr) IServiceZoneDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s serviceZoneDo) Join(table schema.Tabler, on ...field.Expr) IServiceZoneDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s serviceZoneDo) LeftJoin(table schema.Tabler, on ...field.Expr) IServiceZoneDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s serviceZoneDo) RightJoin(table schema.Tabler, on ...field.Expr) IServiceZoneDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s serviceZoneDo) Group(cols ...field.Expr) IServiceZoneDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s serviceZoneDo) Having(conds ...gen.Condition) IServiceZoneDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s serviceZoneDo) Limit(limit int) IServiceZoneDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s serviceZoneDo) Offset(offset int) IServiceZoneDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s serviceZoneDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IServiceZoneDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s serviceZoneDo) Unscoped() IServiceZoneDo {
	return s.withDO(s.DO.Unscoped())
}

func (s serviceZoneDo) Create(values ...*model.ServiceZone) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s serviceZoneDo) CreateInBatches(values []*model.ServiceZone, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s serviceZoneDo) Save(values ...*model.ServiceZone) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s serviceZoneDo) First() (*model.ServiceZone, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceZone), nil
	}
}

func (s serviceZoneDo) Take() (*model.ServiceZone, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceZone), nil
	}
}

func (s serviceZoneDo) Last() (*model.ServiceZone, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceZone), nil
	}
}

func (s serviceZoneDo) Find() ([]*model.ServiceZone, error) {
	result, err := s.DO.Find()
	return result.([]*model.ServiceZone), err
}

func (s serviceZoneDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ServiceZone, err error) {
	buf := make([]*model.ServiceZone, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s serviceZoneDo) FindInBatches(result *[]*model.ServiceZone, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s serviceZoneDo) Attrs(attrs ...field.AssignExpr) IServiceZoneDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s serviceZoneDo) Assign(attrs ...field.AssignExpr) IServiceZoneDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s serviceZoneDo) Joins(fields ...field.RelationField) IServiceZoneDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s serviceZoneDo) Preload(fields ...field.RelationField) IServiceZoneDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s serviceZoneDo) FirstOrInit() (*model.ServiceZone, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceZone), nil
	}
}

func (s serviceZoneDo) FirstOrCreate() (*model.ServiceZone, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceZone), nil
	}
}

func (s serviceZoneDo) FindByPage(offset int, limit int) (result []*model.ServiceZone, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s serviceZoneDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s serviceZoneDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s serviceZoneDo) Delete(models ...*model.ServiceZone) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *serviceZoneDo) withDO(do gen.Dao) *serviceZoneDo {
	s.DO = *do.(*gen.DO)
	return s
}
