// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"community-elderly-care-platform/internal/dao/model"
)

func newServiceStation(db *gorm.DB, opts ...gen.DOOption) serviceStation {
	_serviceStation := serviceStation{}

	_serviceStation.serviceStationDo.UseDB(db, opts...)
	_serviceStation.serviceStationDo.UseModel(&model.ServiceStation{})

	tableName := _serviceStation.serviceStationDo.TableName()
	_serviceStation.ALL = field.NewAsterisk(tableName)
	_serviceStation.ID = field.NewInt64(tableName, "id")
	_serviceStation.Name = field.NewString(tableName, "name")
	_serviceStation.Code = field.NewString(tableName, "code")
	_serviceStation.Address = field.NewString(tableName, "address")
	_serviceStation.Phone = field.NewString(tableName, "phone")
	_serviceStation.Latitude = field.NewFloat64(tableName, "latitude")
	_serviceStation.Longitude = field.NewFloat64(tableName, "longitude")
	_serviceStation.ServiceArea = field.NewString(tableName, "service_area")
	_serviceStation.Capacity = field.NewInt64(tableName, "capacity")
	_serviceStation.WorkHours = field.NewString(tableName, "work_hours")
	_serviceStation.Status = field.NewString(tableName, "status")
	_serviceStation.CreatedAt = field.NewTime(tableName, "created_at")
	_serviceStation.UpdatedAt = field.NewTime(tableName, "updated_at")
	_serviceStation.DeletedAt = field.NewField(tableName, "deleted_at")

	_serviceStation.fillFieldMap()

	return _serviceStation
}

// serviceStation 服务站点表
type serviceStation struct {
	serviceStationDo

	ALL         field.Asterisk
	ID          field.Int64 // 主键ID
	Name        field.String
	Code        field.String
	Address     field.String
	Phone       field.String
	Latitude    field.Float64
	Longitude   field.Float64
	ServiceArea field.String
	Capacity    field.Int64
	WorkHours   field.String
	Status      field.String
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field

	fieldMap map[string]field.Expr
}

func (s serviceStation) Table(newTableName string) *serviceStation {
	s.serviceStationDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s serviceStation) As(alias string) *serviceStation {
	s.serviceStationDo.DO = *(s.serviceStationDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *serviceStation) updateTableName(table string) *serviceStation {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Name = field.NewString(table, "name")
	s.Code = field.NewString(table, "code")
	s.Address = field.NewString(table, "address")
	s.Phone = field.NewString(table, "phone")
	s.Latitude = field.NewFloat64(table, "latitude")
	s.Longitude = field.NewFloat64(table, "longitude")
	s.ServiceArea = field.NewString(table, "service_area")
	s.Capacity = field.NewInt64(table, "capacity")
	s.WorkHours = field.NewString(table, "work_hours")
	s.Status = field.NewString(table, "status")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *serviceStation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *serviceStation) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 14)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["code"] = s.Code
	s.fieldMap["address"] = s.Address
	s.fieldMap["phone"] = s.Phone
	s.fieldMap["latitude"] = s.Latitude
	s.fieldMap["longitude"] = s.Longitude
	s.fieldMap["service_area"] = s.ServiceArea
	s.fieldMap["capacity"] = s.Capacity
	s.fieldMap["work_hours"] = s.WorkHours
	s.fieldMap["status"] = s.Status
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s serviceStation) clone(db *gorm.DB) serviceStation {
	s.serviceStationDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s serviceStation) replaceDB(db *gorm.DB) serviceStation {
	s.serviceStationDo.ReplaceDB(db)
	return s
}

type serviceStationDo struct{ gen.DO }

type IServiceStationDo interface {
	gen.SubQuery
	Debug() IServiceStationDo
	WithContext(ctx context.Context) IServiceStationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IServiceStationDo
	WriteDB() IServiceStationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IServiceStationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IServiceStationDo
	Not(conds ...gen.Condition) IServiceStationDo
	Or(conds ...gen.Condition) IServiceStationDo
	Select(conds ...field.Expr) IServiceStationDo
	Where(conds ...gen.Condition) IServiceStationDo
	Order(conds ...field.Expr) IServiceStationDo
	Distinct(cols ...field.Expr) IServiceStationDo
	Omit(cols ...field.Expr) IServiceStationDo
	Join(table schema.Tabler, on ...field.Expr) IServiceStationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IServiceStationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IServiceStationDo
	Group(cols ...field.Expr) IServiceStationDo
	Having(conds ...gen.Condition) IServiceStationDo
	Limit(limit int) IServiceStationDo
	Offset(offset int) IServiceStationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IServiceStationDo
	Unscoped() IServiceStationDo
	Create(values ...*model.ServiceStation) error
	CreateInBatches(values []*model.ServiceStation, batchSize int) error
	Save(values ...*model.ServiceStation) error
	First() (*model.ServiceStation, error)
	Take() (*model.ServiceStation, error)
	Last() (*model.ServiceStation, error)
	Find() ([]*model.ServiceStation, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ServiceStation, err error)
	FindInBatches(result *[]*model.ServiceStation, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ServiceStation) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IServiceStationDo
	Assign(attrs ...field.AssignExpr) IServiceStationDo
	Joins(fields ...field.RelationField) IServiceStationDo
	Preload(fields ...field.RelationField) IServiceStationDo
	FirstOrInit() (*model.ServiceStation, error)
	FirstOrCreate() (*model.ServiceStation, error)
	FindByPage(offset int, limit int) (result []*model.ServiceStation, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IServiceStationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s serviceStationDo) Debug() IServiceStationDo {
	return s.withDO(s.DO.Debug())
}

func (s serviceStationDo) WithContext(ctx context.Context) IServiceStationDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s serviceStationDo) ReadDB() IServiceStationDo {
	return s.Clauses(dbresolver.Read)
}

func (s serviceStationDo) WriteDB() IServiceStationDo {
	return s.Clauses(dbresolver.Write)
}

func (s serviceStationDo) Session(config *gorm.Session) IServiceStationDo {
	return s.withDO(s.DO.Session(config))
}

func (s serviceStationDo) Clauses(conds ...clause.Expression) IServiceStationDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s serviceStationDo) Returning(value interface{}, columns ...string) IServiceStationDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s serviceStationDo) Not(conds ...gen.Condition) IServiceStationDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s serviceStationDo) Or(conds ...gen.Condition) IServiceStationDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s serviceStationDo) Select(conds ...field.Expr) IServiceStationDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s serviceStationDo) Where(conds ...gen.Condition) IServiceStationDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s serviceStationDo) Order(conds ...field.Expr) IServiceStationDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s serviceStationDo) Distinct(cols ...field.Expr) IServiceStationDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s serviceStationDo) Omit(cols ...field.Expr) IServiceStationDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s serviceStationDo) Join(table schema.Tabler, on ...field.Expr) IServiceStationDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s serviceStationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IServiceStationDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s serviceStationDo) RightJoin(table schema.Tabler, on ...field.Expr) IServiceStationDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s serviceStationDo) Group(cols ...field.Expr) IServiceStationDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s serviceStationDo) Having(conds ...gen.Condition) IServiceStationDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s serviceStationDo) Limit(limit int) IServiceStationDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s serviceStationDo) Offset(offset int) IServiceStationDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s serviceStationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IServiceStationDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s serviceStationDo) Unscoped() IServiceStationDo {
	return s.withDO(s.DO.Unscoped())
}

func (s serviceStationDo) Create(values ...*model.ServiceStation) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s serviceStationDo) CreateInBatches(values []*model.ServiceStation, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s serviceStationDo) Save(values ...*model.ServiceStation) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s serviceStationDo) First() (*model.ServiceStation, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceStation), nil
	}
}

func (s serviceStationDo) Take() (*model.ServiceStation, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceStation), nil
	}
}

func (s serviceStationDo) Last() (*model.ServiceStation, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceStation), nil
	}
}

func (s serviceStationDo) Find() ([]*model.ServiceStation, error) {
	result, err := s.DO.Find()
	return result.([]*model.ServiceStation), err
}

func (s serviceStationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ServiceStation, err error) {
	buf := make([]*model.ServiceStation, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s serviceStationDo) FindInBatches(result *[]*model.ServiceStation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s serviceStationDo) Attrs(attrs ...field.AssignExpr) IServiceStationDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s serviceStationDo) Assign(attrs ...field.AssignExpr) IServiceStationDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s serviceStationDo) Joins(fields ...field.RelationField) IServiceStationDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s serviceStationDo) Preload(fields ...field.RelationField) IServiceStationDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s serviceStationDo) FirstOrInit() (*model.ServiceStation, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceStation), nil
	}
}

func (s serviceStationDo) FirstOrCreate() (*model.ServiceStation, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceStation), nil
	}
}

func (s serviceStationDo) FindByPage(offset int, limit int) (result []*model.ServiceStation, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s serviceStationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s serviceStationDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s serviceStationDo) Delete(models ...*model.ServiceStation) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *serviceStationDo) withDO(do gen.Dao) *serviceStationDo {
	s.DO = *do.(*gen.DO)
	return s
}
