// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"community-elderly-care-platform/internal/dao/model"
)

func newServiceRequest(db *gorm.DB, opts ...gen.DOOption) serviceRequest {
	_serviceRequest := serviceRequest{}

	_serviceRequest.serviceRequestDo.UseDB(db, opts...)
	_serviceRequest.serviceRequestDo.UseModel(&model.ServiceRequest{})

	tableName := _serviceRequest.serviceRequestDo.TableName()
	_serviceRequest.ALL = field.NewAsterisk(tableName)
	_serviceRequest.ID = field.NewInt64(tableName, "id")
	_serviceRequest.RequestNo = field.NewString(tableName, "request_no")
	_serviceRequest.UserID = field.NewInt64(tableName, "user_id")
	_serviceRequest.ServiceType = field.NewString(tableName, "service_type")
	_serviceRequest.Status = field.NewString(tableName, "status")
	_serviceRequest.Description = field.NewString(tableName, "description")
	_serviceRequest.SubmitLocationLat = field.NewFloat64(tableName, "submit_location_lat")
	_serviceRequest.SubmitLocationLng = field.NewFloat64(tableName, "submit_location_lng")
	_serviceRequest.ContactName = field.NewString(tableName, "contact_name")
	_serviceRequest.ContactPhone = field.NewString(tableName, "contact_phone")
	_serviceRequest.Address = field.NewString(tableName, "address")
	_serviceRequest.AppointmentTime = field.NewTime(tableName, "appointment_time")
	_serviceRequest.Urgency = field.NewString(tableName, "urgency")
	_serviceRequest.StationID = field.NewInt64(tableName, "station_id")
	_serviceRequest.RejectReason = field.NewString(tableName, "reject_reason")
	_serviceRequest.Images = field.NewString(tableName, "images")
	_serviceRequest.CreatedAt = field.NewTime(tableName, "created_at")
	_serviceRequest.UpdatedAt = field.NewTime(tableName, "updated_at")
	_serviceRequest.DeletedAt = field.NewField(tableName, "deleted_at")
	_serviceRequest.Rating = field.NewInt64(tableName, "rating")
	_serviceRequest.Feedback = field.NewString(tableName, "feedback")

	_serviceRequest.fillFieldMap()

	return _serviceRequest
}

// serviceRequest 服务需求表
type serviceRequest struct {
	serviceRequestDo

	ALL               field.Asterisk
	ID                field.Int64 // 主键ID
	RequestNo         field.String
	UserID            field.Int64
	ServiceType       field.String
	Status            field.String
	Description       field.String
	SubmitLocationLat field.Float64
	SubmitLocationLng field.Float64
	ContactName       field.String
	ContactPhone      field.String
	Address           field.String
	AppointmentTime   field.Time
	Urgency           field.String
	StationID         field.Int64
	RejectReason      field.String
	Images            field.String
	CreatedAt         field.Time
	UpdatedAt         field.Time
	DeletedAt         field.Field
	Rating            field.Int64
	Feedback          field.String

	fieldMap map[string]field.Expr
}

func (s serviceRequest) Table(newTableName string) *serviceRequest {
	s.serviceRequestDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s serviceRequest) As(alias string) *serviceRequest {
	s.serviceRequestDo.DO = *(s.serviceRequestDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *serviceRequest) updateTableName(table string) *serviceRequest {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.RequestNo = field.NewString(table, "request_no")
	s.UserID = field.NewInt64(table, "user_id")
	s.ServiceType = field.NewString(table, "service_type")
	s.Status = field.NewString(table, "status")
	s.Description = field.NewString(table, "description")
	s.SubmitLocationLat = field.NewFloat64(table, "submit_location_lat")
	s.SubmitLocationLng = field.NewFloat64(table, "submit_location_lng")
	s.ContactName = field.NewString(table, "contact_name")
	s.ContactPhone = field.NewString(table, "contact_phone")
	s.Address = field.NewString(table, "address")
	s.AppointmentTime = field.NewTime(table, "appointment_time")
	s.Urgency = field.NewString(table, "urgency")
	s.StationID = field.NewInt64(table, "station_id")
	s.RejectReason = field.NewString(table, "reject_reason")
	s.Images = field.NewString(table, "images")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.Rating = field.NewInt64(table, "rating")
	s.Feedback = field.NewString(table, "feedback")

	s.fillFieldMap()

	return s
}

func (s *serviceRequest) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *serviceRequest) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 21)
	s.fieldMap["id"] = s.ID
	s.fieldMap["request_no"] = s.RequestNo
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["service_type"] = s.ServiceType
	s.fieldMap["status"] = s.Status
	s.fieldMap["description"] = s.Description
	s.fieldMap["submit_location_lat"] = s.SubmitLocationLat
	s.fieldMap["submit_location_lng"] = s.SubmitLocationLng
	s.fieldMap["contact_name"] = s.ContactName
	s.fieldMap["contact_phone"] = s.ContactPhone
	s.fieldMap["address"] = s.Address
	s.fieldMap["appointment_time"] = s.AppointmentTime
	s.fieldMap["urgency"] = s.Urgency
	s.fieldMap["station_id"] = s.StationID
	s.fieldMap["reject_reason"] = s.RejectReason
	s.fieldMap["images"] = s.Images
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["rating"] = s.Rating
	s.fieldMap["feedback"] = s.Feedback
}

func (s serviceRequest) clone(db *gorm.DB) serviceRequest {
	s.serviceRequestDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s serviceRequest) replaceDB(db *gorm.DB) serviceRequest {
	s.serviceRequestDo.ReplaceDB(db)
	return s
}

type serviceRequestDo struct{ gen.DO }

type IServiceRequestDo interface {
	gen.SubQuery
	Debug() IServiceRequestDo
	WithContext(ctx context.Context) IServiceRequestDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IServiceRequestDo
	WriteDB() IServiceRequestDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IServiceRequestDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IServiceRequestDo
	Not(conds ...gen.Condition) IServiceRequestDo
	Or(conds ...gen.Condition) IServiceRequestDo
	Select(conds ...field.Expr) IServiceRequestDo
	Where(conds ...gen.Condition) IServiceRequestDo
	Order(conds ...field.Expr) IServiceRequestDo
	Distinct(cols ...field.Expr) IServiceRequestDo
	Omit(cols ...field.Expr) IServiceRequestDo
	Join(table schema.Tabler, on ...field.Expr) IServiceRequestDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IServiceRequestDo
	RightJoin(table schema.Tabler, on ...field.Expr) IServiceRequestDo
	Group(cols ...field.Expr) IServiceRequestDo
	Having(conds ...gen.Condition) IServiceRequestDo
	Limit(limit int) IServiceRequestDo
	Offset(offset int) IServiceRequestDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IServiceRequestDo
	Unscoped() IServiceRequestDo
	Create(values ...*model.ServiceRequest) error
	CreateInBatches(values []*model.ServiceRequest, batchSize int) error
	Save(values ...*model.ServiceRequest) error
	First() (*model.ServiceRequest, error)
	Take() (*model.ServiceRequest, error)
	Last() (*model.ServiceRequest, error)
	Find() ([]*model.ServiceRequest, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ServiceRequest, err error)
	FindInBatches(result *[]*model.ServiceRequest, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ServiceRequest) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IServiceRequestDo
	Assign(attrs ...field.AssignExpr) IServiceRequestDo
	Joins(fields ...field.RelationField) IServiceRequestDo
	Preload(fields ...field.RelationField) IServiceRequestDo
	FirstOrInit() (*model.ServiceRequest, error)
	FirstOrCreate() (*model.ServiceRequest, error)
	FindByPage(offset int, limit int) (result []*model.ServiceRequest, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IServiceRequestDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s serviceRequestDo) Debug() IServiceRequestDo {
	return s.withDO(s.DO.Debug())
}

func (s serviceRequestDo) WithContext(ctx context.Context) IServiceRequestDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s serviceRequestDo) ReadDB() IServiceRequestDo {
	return s.Clauses(dbresolver.Read)
}

func (s serviceRequestDo) WriteDB() IServiceRequestDo {
	return s.Clauses(dbresolver.Write)
}

func (s serviceRequestDo) Session(config *gorm.Session) IServiceRequestDo {
	return s.withDO(s.DO.Session(config))
}

func (s serviceRequestDo) Clauses(conds ...clause.Expression) IServiceRequestDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s serviceRequestDo) Returning(value interface{}, columns ...string) IServiceRequestDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s serviceRequestDo) Not(conds ...gen.Condition) IServiceRequestDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s serviceRequestDo) Or(conds ...gen.Condition) IServiceRequestDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s serviceRequestDo) Select(conds ...field.Expr) IServiceRequestDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s serviceRequestDo) Where(conds ...gen.Condition) IServiceRequestDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s serviceRequestDo) Order(conds ...field.Expr) IServiceRequestDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s serviceRequestDo) Distinct(cols ...field.Expr) IServiceRequestDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s serviceRequestDo) Omit(cols ...field.Expr) IServiceRequestDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s serviceRequestDo) Join(table schema.Tabler, on ...field.Expr) IServiceRequestDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s serviceRequestDo) LeftJoin(table schema.Tabler, on ...field.Expr) IServiceRequestDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s serviceRequestDo) RightJoin(table schema.Tabler, on ...field.Expr) IServiceRequestDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s serviceRequestDo) Group(cols ...field.Expr) IServiceRequestDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s serviceRequestDo) Having(conds ...gen.Condition) IServiceRequestDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s serviceRequestDo) Limit(limit int) IServiceRequestDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s serviceRequestDo) Offset(offset int) IServiceRequestDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s serviceRequestDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IServiceRequestDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s serviceRequestDo) Unscoped() IServiceRequestDo {
	return s.withDO(s.DO.Unscoped())
}

func (s serviceRequestDo) Create(values ...*model.ServiceRequest) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s serviceRequestDo) CreateInBatches(values []*model.ServiceRequest, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s serviceRequestDo) Save(values ...*model.ServiceRequest) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s serviceRequestDo) First() (*model.ServiceRequest, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceRequest), nil
	}
}

func (s serviceRequestDo) Take() (*model.ServiceRequest, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceRequest), nil
	}
}

func (s serviceRequestDo) Last() (*model.ServiceRequest, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceRequest), nil
	}
}

func (s serviceRequestDo) Find() ([]*model.ServiceRequest, error) {
	result, err := s.DO.Find()
	return result.([]*model.ServiceRequest), err
}

func (s serviceRequestDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ServiceRequest, err error) {
	buf := make([]*model.ServiceRequest, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s serviceRequestDo) FindInBatches(result *[]*model.ServiceRequest, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s serviceRequestDo) Attrs(attrs ...field.AssignExpr) IServiceRequestDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s serviceRequestDo) Assign(attrs ...field.AssignExpr) IServiceRequestDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s serviceRequestDo) Joins(fields ...field.RelationField) IServiceRequestDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s serviceRequestDo) Preload(fields ...field.RelationField) IServiceRequestDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s serviceRequestDo) FirstOrInit() (*model.ServiceRequest, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceRequest), nil
	}
}

func (s serviceRequestDo) FirstOrCreate() (*model.ServiceRequest, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceRequest), nil
	}
}

func (s serviceRequestDo) FindByPage(offset int, limit int) (result []*model.ServiceRequest, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s serviceRequestDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s serviceRequestDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s serviceRequestDo) Delete(models ...*model.ServiceRequest) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *serviceRequestDo) withDO(do gen.Dao) *serviceRequestDo {
	s.DO = *do.(*gen.DO)
	return s
}
