// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"community-elderly-care-platform/internal/dao/model"
)

func newTaskAssignment(db *gorm.DB, opts ...gen.DOOption) taskAssignment {
	_taskAssignment := taskAssignment{}

	_taskAssignment.taskAssignmentDo.UseDB(db, opts...)
	_taskAssignment.taskAssignmentDo.UseModel(&model.TaskAssignment{})

	tableName := _taskAssignment.taskAssignmentDo.TableName()
	_taskAssignment.ALL = field.NewAsterisk(tableName)
	_taskAssignment.ID = field.NewInt64(tableName, "id")
	_taskAssignment.RequestID = field.NewInt64(tableName, "request_id")
	_taskAssignment.StationID = field.NewInt64(tableName, "station_id")
	_taskAssignment.StaffID = field.NewInt64(tableName, "staff_id")
	_taskAssignment.Status = field.NewString(tableName, "status")
	_taskAssignment.ClaimedAt = field.NewTime(tableName, "claimed_at")
	_taskAssignment.CompletedAt = field.NewTime(tableName, "completed_at")
	_taskAssignment.Rating = field.NewInt64(tableName, "rating")
	_taskAssignment.Feedback = field.NewString(tableName, "feedback")
	_taskAssignment.StaffNotes = field.NewString(tableName, "staff_notes")
	_taskAssignment.Images = field.NewString(tableName, "images")
	_taskAssignment.CreatedAt = field.NewTime(tableName, "created_at")
	_taskAssignment.UpdatedAt = field.NewTime(tableName, "updated_at")
	_taskAssignment.DeletedAt = field.NewField(tableName, "deleted_at")

	_taskAssignment.fillFieldMap()

	return _taskAssignment
}

// taskAssignment 任务分配表
type taskAssignment struct {
	taskAssignmentDo

	ALL         field.Asterisk
	ID          field.Int64 // 主键ID
	RequestID   field.Int64
	StationID   field.Int64
	StaffID     field.Int64
	Status      field.String
	ClaimedAt   field.Time
	CompletedAt field.Time
	Rating      field.Int64
	Feedback    field.String
	StaffNotes  field.String
	Images      field.String
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field

	fieldMap map[string]field.Expr
}

func (t taskAssignment) Table(newTableName string) *taskAssignment {
	t.taskAssignmentDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t taskAssignment) As(alias string) *taskAssignment {
	t.taskAssignmentDo.DO = *(t.taskAssignmentDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *taskAssignment) updateTableName(table string) *taskAssignment {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.RequestID = field.NewInt64(table, "request_id")
	t.StationID = field.NewInt64(table, "station_id")
	t.StaffID = field.NewInt64(table, "staff_id")
	t.Status = field.NewString(table, "status")
	t.ClaimedAt = field.NewTime(table, "claimed_at")
	t.CompletedAt = field.NewTime(table, "completed_at")
	t.Rating = field.NewInt64(table, "rating")
	t.Feedback = field.NewString(table, "feedback")
	t.StaffNotes = field.NewString(table, "staff_notes")
	t.Images = field.NewString(table, "images")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")

	t.fillFieldMap()

	return t
}

func (t *taskAssignment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *taskAssignment) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 14)
	t.fieldMap["id"] = t.ID
	t.fieldMap["request_id"] = t.RequestID
	t.fieldMap["station_id"] = t.StationID
	t.fieldMap["staff_id"] = t.StaffID
	t.fieldMap["status"] = t.Status
	t.fieldMap["claimed_at"] = t.ClaimedAt
	t.fieldMap["completed_at"] = t.CompletedAt
	t.fieldMap["rating"] = t.Rating
	t.fieldMap["feedback"] = t.Feedback
	t.fieldMap["staff_notes"] = t.StaffNotes
	t.fieldMap["images"] = t.Images
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
}

func (t taskAssignment) clone(db *gorm.DB) taskAssignment {
	t.taskAssignmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t taskAssignment) replaceDB(db *gorm.DB) taskAssignment {
	t.taskAssignmentDo.ReplaceDB(db)
	return t
}

type taskAssignmentDo struct{ gen.DO }

type ITaskAssignmentDo interface {
	gen.SubQuery
	Debug() ITaskAssignmentDo
	WithContext(ctx context.Context) ITaskAssignmentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITaskAssignmentDo
	WriteDB() ITaskAssignmentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITaskAssignmentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITaskAssignmentDo
	Not(conds ...gen.Condition) ITaskAssignmentDo
	Or(conds ...gen.Condition) ITaskAssignmentDo
	Select(conds ...field.Expr) ITaskAssignmentDo
	Where(conds ...gen.Condition) ITaskAssignmentDo
	Order(conds ...field.Expr) ITaskAssignmentDo
	Distinct(cols ...field.Expr) ITaskAssignmentDo
	Omit(cols ...field.Expr) ITaskAssignmentDo
	Join(table schema.Tabler, on ...field.Expr) ITaskAssignmentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITaskAssignmentDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITaskAssignmentDo
	Group(cols ...field.Expr) ITaskAssignmentDo
	Having(conds ...gen.Condition) ITaskAssignmentDo
	Limit(limit int) ITaskAssignmentDo
	Offset(offset int) ITaskAssignmentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskAssignmentDo
	Unscoped() ITaskAssignmentDo
	Create(values ...*model.TaskAssignment) error
	CreateInBatches(values []*model.TaskAssignment, batchSize int) error
	Save(values ...*model.TaskAssignment) error
	First() (*model.TaskAssignment, error)
	Take() (*model.TaskAssignment, error)
	Last() (*model.TaskAssignment, error)
	Find() ([]*model.TaskAssignment, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TaskAssignment, err error)
	FindInBatches(result *[]*model.TaskAssignment, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TaskAssignment) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITaskAssignmentDo
	Assign(attrs ...field.AssignExpr) ITaskAssignmentDo
	Joins(fields ...field.RelationField) ITaskAssignmentDo
	Preload(fields ...field.RelationField) ITaskAssignmentDo
	FirstOrInit() (*model.TaskAssignment, error)
	FirstOrCreate() (*model.TaskAssignment, error)
	FindByPage(offset int, limit int) (result []*model.TaskAssignment, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITaskAssignmentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t taskAssignmentDo) Debug() ITaskAssignmentDo {
	return t.withDO(t.DO.Debug())
}

func (t taskAssignmentDo) WithContext(ctx context.Context) ITaskAssignmentDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t taskAssignmentDo) ReadDB() ITaskAssignmentDo {
	return t.Clauses(dbresolver.Read)
}

func (t taskAssignmentDo) WriteDB() ITaskAssignmentDo {
	return t.Clauses(dbresolver.Write)
}

func (t taskAssignmentDo) Session(config *gorm.Session) ITaskAssignmentDo {
	return t.withDO(t.DO.Session(config))
}

func (t taskAssignmentDo) Clauses(conds ...clause.Expression) ITaskAssignmentDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t taskAssignmentDo) Returning(value interface{}, columns ...string) ITaskAssignmentDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t taskAssignmentDo) Not(conds ...gen.Condition) ITaskAssignmentDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t taskAssignmentDo) Or(conds ...gen.Condition) ITaskAssignmentDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t taskAssignmentDo) Select(conds ...field.Expr) ITaskAssignmentDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t taskAssignmentDo) Where(conds ...gen.Condition) ITaskAssignmentDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t taskAssignmentDo) Order(conds ...field.Expr) ITaskAssignmentDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t taskAssignmentDo) Distinct(cols ...field.Expr) ITaskAssignmentDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t taskAssignmentDo) Omit(cols ...field.Expr) ITaskAssignmentDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t taskAssignmentDo) Join(table schema.Tabler, on ...field.Expr) ITaskAssignmentDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t taskAssignmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITaskAssignmentDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t taskAssignmentDo) RightJoin(table schema.Tabler, on ...field.Expr) ITaskAssignmentDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t taskAssignmentDo) Group(cols ...field.Expr) ITaskAssignmentDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t taskAssignmentDo) Having(conds ...gen.Condition) ITaskAssignmentDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t taskAssignmentDo) Limit(limit int) ITaskAssignmentDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t taskAssignmentDo) Offset(offset int) ITaskAssignmentDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t taskAssignmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskAssignmentDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t taskAssignmentDo) Unscoped() ITaskAssignmentDo {
	return t.withDO(t.DO.Unscoped())
}

func (t taskAssignmentDo) Create(values ...*model.TaskAssignment) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t taskAssignmentDo) CreateInBatches(values []*model.TaskAssignment, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t taskAssignmentDo) Save(values ...*model.TaskAssignment) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t taskAssignmentDo) First() (*model.TaskAssignment, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskAssignment), nil
	}
}

func (t taskAssignmentDo) Take() (*model.TaskAssignment, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskAssignment), nil
	}
}

func (t taskAssignmentDo) Last() (*model.TaskAssignment, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskAssignment), nil
	}
}

func (t taskAssignmentDo) Find() ([]*model.TaskAssignment, error) {
	result, err := t.DO.Find()
	return result.([]*model.TaskAssignment), err
}

func (t taskAssignmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TaskAssignment, err error) {
	buf := make([]*model.TaskAssignment, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t taskAssignmentDo) FindInBatches(result *[]*model.TaskAssignment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t taskAssignmentDo) Attrs(attrs ...field.AssignExpr) ITaskAssignmentDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t taskAssignmentDo) Assign(attrs ...field.AssignExpr) ITaskAssignmentDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t taskAssignmentDo) Joins(fields ...field.RelationField) ITaskAssignmentDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t taskAssignmentDo) Preload(fields ...field.RelationField) ITaskAssignmentDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t taskAssignmentDo) FirstOrInit() (*model.TaskAssignment, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskAssignment), nil
	}
}

func (t taskAssignmentDo) FirstOrCreate() (*model.TaskAssignment, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskAssignment), nil
	}
}

func (t taskAssignmentDo) FindByPage(offset int, limit int) (result []*model.TaskAssignment, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t taskAssignmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t taskAssignmentDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t taskAssignmentDo) Delete(models ...*model.TaskAssignment) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *taskAssignmentDo) withDO(do gen.Dao) *taskAssignmentDo {
	t.DO = *do.(*gen.DO)
	return t
}
